index:
    path: /
    controller: App\Controller\BlogController::index

theme_script:
    path: theme/script/{filename}
    controller: App\Controller\ThemeAssetController::getScript

theme_style:
    path: theme/style/{filename}
    controller: App\Controller\ThemeAssetController::getStylesheet
