#ckfinder
ckfinder_connector:
    resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
    prefix:   /

################

index:
    path: /
    controller: App\Controller\MainController::index

theme_asset:
    path: assets/theme/{filename}
    controller: App\Controller\DynamicAssetController::getThemeAsset
    requirements:
        filename: .+

plugin_asset:
    path: assets/plugin/{plugin}/{filename}
    controller: App\Controller\DynamicAssetController::getPluginAsset
    requirements:
        filename: .+


#ADMIN PANEL

plugin_routes:
    resource: app.manager.plugin::loadPluginRoutes
    type: service

admin_logout:
    path: admin/logout
    controller: App\Controller\MainController::adminLogout

admin_login:
    path: admin/login
    controller: App\Controller\MainController::adminLogin

admin_panel:
    path: admin/
    controller: App\Controller\MainController::getAdminPanelMain

admin_panel_path:
    path: admin/{path}
    controller: App\Controller\MainController::getAdminPanel
    defaults:
        path: ''
    requirements:
        path: .+



##################
page:
    path: /{pageid}
    controller: App\Controller\MainController::getPage


