#ckfinder
ckfinder_connector:
    resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
    prefix:   /

################

index:
    path: /
    controller: App\Controller\MainController::index

theme_asset:
    path: assets/theme/{filename}
    controller: App\Controller\DynamicAssetController::getThemeAsset
    requirements:
        filename: .+

plugin_asset:
    path: assets/plugin/{plugin}/{filename}
    controller: App\Controller\DynamicAssetController::getPluginAsset
    requirements:
        filename: .+


#ADMIN PANEL

install:
    path: /install
    controller: App\Controller\AdminController::installSite

initialize:
    path: /install/init
    controller: App\Controller\AdminController::initSite

db_check:
    path: /install/checkdb
    controller: App\Controller\AdminController::checkDatabase

plugin_routes:
    resource: app.manager.plugin::loadPluginRoutes
    type: service

admin_panel:
    path: admin
    controller: App\Controller\AdminController::getPanelMain

admin_panel_path:
    path: admin/{path}
    controller: App\Controller\AdminController::getPanel
    defaults:
        path: ''
    requirements:
        path: .+


test:
    path: /test
    controller: App\Controller\MainController::test

##################
post:
    path: /post/{category}/{id}
    controller: App\Controller\MainController::getPost

page:
    path: /{pageid}
    controller: App\Controller\MainController::getPage


