index:
    path: /
    controller: App\Controller\BlogController::index

theme_script:
    path: theme/js/{filename}
    controller: App\Controller\ThemeAssetController::getScript

theme_style:
    path: theme/css/{filename}
    controller: App\Controller\ThemeAssetController::getStylesheet

