#HWI OAUTH


################

index:
    path: /
    controller: App\Controller\MainController::index

theme_script:
    path: theme/js/{filename}
    controller: App\Controller\ThemeAssetController::getScript

theme_style:
    path: theme/css/{filename}
    controller: App\Controller\ThemeAssetController::getStylesheet

theme_asset:
    path: theme/asset/{filename}
    controller: App\Controller\ThemeAssetController::getAsset

img:
    path: img/{filename}
    controller: App\Controller\UploadedImageController::getImage

util_asset:
    path: util/{filename}
    controller: App\Controller\UtilAssetController::getAsset


#CONSTRUCTOR

validate_argument:
    path: constructor/data/{module_name}/{arg_name}/validate
    controller: App\Controller\ConstructorController::validateModuleArgument

argument_list:
    path: constructor/data/{module_name}/{arg_name}/list
    controller: App\Controller\ConstructorController::getModuleArgumentList

block_get:
    path: constructor/block/{page_id}/{block_name}/set
    controller: App\Controller\ConstructorController::setBlock

block_set:
    path: constructor/block/{page_id}/{block_name}/get
    controller: App\Controller\ConstructorController::getBlock

constructor_data:
    path: constructor/blocks
    controller: App\Controller\ConstructorController::getConstructorData

#ADMIN

admin_panel:
    path: admin
    controller: App\Controller\ConstructorController::adminPanel


