#HWI OAUTH


################

index:
    path: /
    controller: App\Controller\MainController::index

theme_script:
    path: theme/js/{filename}
    controller: App\Controller\ThemeAssetController::getScript

theme_style:
    path: theme/css/{filename}
    controller: App\Controller\ThemeAssetController::getStylesheet

theme_asset:
    path: theme/asset/{filename}
    controller: App\Controller\ThemeAssetController::getAsset

img:
    path: img/{filename}
    controller: App\Controller\UploadedImageController::getImage


#CONSTRUCTOR

validate_argument:
    path: constructor_data/{module_name}/{arg_name}/validate
    controller: App\Controller\ConstructorController::validateModuleArgument

argument_list:
    path: constructor_data/{module_name}/{arg_name}/list
    controller: App\Controller\ConstructorController::getModuleArgumentList

admin_panel:
    path: panel
    controller: App\Controller\ConstructorController::adminPanel


