#artgris
artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /manager

################

index:
    path: /
    controller: App\Controller\MainController::index

theme_script:
    path: theme/js/{filename}
    controller: App\Controller\ThemeAssetController::getScript

theme_style:
    path: theme/css/{filename}
    controller: App\Controller\ThemeAssetController::getStylesheet

theme_asset:
    path: theme/asset/{filename}
    controller: App\Controller\ThemeAssetController::getAsset

util_asset:
    path: util/{filename}
    controller: App\Controller\UtilAssetController::getAsset


#CONSTRUCTOR

validate_argument:
    path: constructor/data/{module_name}/{arg_name}/validate
    controller: App\Controller\ConstructorController::validateModuleArgument

argument_list:
    path: constructor/data/{module_name}/{arg_name}/list
    controller: App\Controller\ConstructorController::getModuleArgumentList

page_update:
    path: constructor/page/{page_id}/update
    controller: App\Controller\ConstructorController::updatePage

page_remove:
    path: constructor/page/{page_id}/remove
    controller: App\Controller\ConstructorController::removePage

page_create:
    path: constructor/page/{page_id}/create
    controller: App\Controller\ConstructorController::createPage


#ADMIN

admin_logout:
    path: admin/logout
    controller: App\Controller\ConstructorController::null

admin_login:
    path: admin
    controller: App\Controller\ConstructorController::null

############
page:
    path: /{pageid}
    controller: App\Controller\MainController::getPage


