main_template: 'page.html.twig'
blocks:
  header_menu:
    active: true
    accepted_formats:
      - MenuFormat
    module: 
      module: menu
      menu: 'nav-menu'
  left_sidebar1:
    active: true
    accepted_formats:
      - TextFormat
      - MenuFormat
      - FormFormat
    module:
      module: menu
      menu: 'nav-menu'
