blocks:
  top-menu:
    active: true
    accepted-formats:
      - MenuFormat
    module: 
      module: menu
      menu: 'nav-menu'
    settings:
      color:
  left-sidebar1:
    active: true
    accepted-formats:
      - ListFormat
      - MenuFormat
      - FormFormat
    module:
      module: null
  left-sidebar2:
    active: false
    accepted-formats:
      - ListFormat
      - MenuFormat
      - FormFormat
    module:
      module: null
  left-sidebar3:
    active: false
    accepted-formats:
      - ListFormat
      - MenuFormat
      - FormFormat
    module:
      module: null